name: Build

on:
  workflow_dispatch:

jobs:
  build: 
    name: Build package 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Setup Rust
        uses: actions/rust